name: Build Test

on:
    pull_request: {}
    push: {}

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ^1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        path: go/src/github.com/container-storage-interface/spec

    - name: Build Test
      run: |
        export GOPATH=${{ github.workspace }}/go
        cd go/src/github.com/container-storage-interface/spec
        make
